Opla/opla

webapp/.eslintrc.json
webapp/components/common/SplitView/index.tsx
webapp/context/index.tsx
webapp/types/index.ts
webapp/utils/backend/index.ts
webapp/utils/dataStorage.ts
webapp/utils/modalsProvider.tsx

Also remove eslint inline patches

chore: use type instead of interface

---

webapp/components/models/Model.tsx
webapp/components/models/index.tsx
webapp/utils/data/models.ts

When a model is downloading we can't uninstall it
Also for a local model don't display downloadables

feat: display model is downloading

---

webapp/components/providers/Provider.tsx
webapp/components/ui/textarea.tsx
webapp/hooks/useBackend.ts
webapp/native/src/data/mod.rs
webapp/native/src/data/model/mod.rs
webapp/native/src/downloader.rs
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/native/src/store.rs
webapp/native/src/utils.rs

All except in async funcs /callbacks

fix: remove unwrap

---

webapp/native/src/data/mod.rs
webapp/native/src/downloader.rs
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/native/src/store.rs
webapp/native/src/utils.rs

fix: replace last unwrap using match or if

fix: replace expect with map ? or match

---

webapp/components/threads/Thread.tsx
webapp/hooks/useAutoResizeTextArea.ts
webapp/types/index.ts

feat: save current prompt in conversation
feat: one loading / error state per conversation

fix: make each conversation prompt unique

---

webapp/components/threads/Message.tsx
webapp/components/threads/Prompt.tsx
webapp/components/threads/Thread.tsx
webapp/hooks/useAutoResizeTextArea.ts

fix: textarea height
feat: message with "..." animated

Fix: clear prompt before sending

---

webapp/components/common/Statusbar/index.tsx

feat: display currently used model in status bar

---

webapp/components/threads/Settings.tsx
webapp/types/index.ts

feat: add a note for a conversation

---

webapp/components/common/Card/index.tsx
webapp/components/common/SplitView/index.tsx
webapp/components/providers/Explorer.tsx
webapp/components/providers/Toolbar.tsx
webapp/components/providers/opla/Actions.tsx
webapp/components/ui/dialog.tsx
webapp/modals/settings/storage/index.tsx
webapp/modals/templates/NewProvider.tsx

feat: replace all buttons by shadcn/ui Button

---

webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/native/src/data/model/mod.rs
webapp/types/index.ts
webapp/utils/data/models.ts
webapp/utils/providers/opla/index.ts

feat: add system prop for model/conversation

---

Cargo.lock
webapp/components/Layout.tsx
webapp/components/common/Sidebar/SidebarItems.tsx
webapp/components/common/Sidebar/index.tsx
webapp/components/threads/index.tsx
webapp/hooks/useBackend.ts
webapp/native/Cargo.toml
webapp/native/assets/opla_default_config.json
webapp/native/src/main.rs
webapp/native/src/store.rs
webapp/native/tauri.conf.json
webapp/pages/_app.tsx
webapp/pages/index.tsx
webapp/types/index.ts
webapp/utils/backend/commands.ts
webapp/utils/backend/connect.ts
webapp/utils/constants.ts
webapp/utils/string.ts
webapp/utils/tauri.ts

feat: save/restore window size, page and others settings

---

webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/utils/data/models.ts

feat: wait for server to start

---

webapp/components/threads/Thread.tsx
webapp/hooks/useBackend.ts
webapp/native/src/main.rs
webapp/native/src/server.rs

fix: waiting for server reload

---

webapp/components/common/Sidebar/index.tsx
webapp/components/threads/Message.tsx
webapp/hooks/useMarkdownProcessor.tsx

fix: markdown thead error
cleanup Message markdown

fix: sidebar nav

---

package-lock.json
webapp/components/Layout.tsx
webapp/components/common/Markdown/Latex.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/components/ui/Toast/index.tsx
webapp/components/ui/sonner.tsx
webapp/hooks/useDataStorage.ts
webapp/hooks/useFetch.ts
webapp/package.json
webapp/utils/backend/commands.ts
webapp/utils/dataStorage.ts

feat: display errors using Toaster

---

webapp/components/common/PromptCard/index.tsx
webapp/components/threads/PromptsGrid.tsx
webapp/components/threads/Thread.tsx
webapp/types/index.ts

feat: display prompt suggestions

---

webapp/components/common/Sidebar/SidebarItems.tsx
webapp/components/common/Sidebar/index.tsx
webapp/types/index.ts
webapp/utils/constants.ts

feat: display dropdown menu for sidebar settings

---

webapp/components/Layout.tsx
webapp/components/common/ShortCut/index.tsx
webapp/components/common/Sidebar/SidebarItem.tsx
webapp/components/common/Sidebar/SidebarItems.tsx
webapp/components/common/Sidebar/index.tsx
webapp/components/models/NewLocalModel.tsx
webapp/components/threads/Explorer.tsx
webapp/components/threads/Prompt.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/components/threads/index.tsx
webapp/hooks/useRegisterModals.tsx
webapp/hooks/useShortcuts.tsx
webapp/types/index.ts
webapp/utils/constants.ts

fix: use enum for shortcuts command

---

webapp/components/threads/Prompt.tsx
webapp/components/threads/Thread.tsx

fix: onfocus caret position
#155

fix: only one temp conversation

---

webapp/components/common/Sidebar/SidebarItems.tsx
webapp/components/common/Sidebar/index.tsx

feat: icons in settings dropdown menu

---

package-lock.json
webapp/components/common/Parameter/index.tsx
webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/components/ui/switch.tsx
webapp/hooks/useBackendContext.tsx
webapp/native/src/llm.rs
webapp/package.json
webapp/types/index.ts
webapp/utils/providers/index.ts
webapp/utils/providers/openai/index.ts
webapp/utils/providers/opla/index.ts

feat: Presets

---

webapp/components/threads/Settings.tsx
webapp/utils/providers/openai/index.ts
webapp/utils/providers/opla/index.ts

feat: add LLama.cpp parameters definition

---

webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/native/src/llm.rs
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/types/index.ts
webapp/utils/providers/index.ts
webapp/utils/providers/openai/index.ts
webapp/utils/providers/opla/index.ts

feat: serialize arbitrary llm completion parameters

---

webapp/components/common/Statusbar/index.tsx
webapp/components/threads/Thread.tsx
webapp/context/index.tsx
webapp/native/src/error.rs
webapp/native/src/llm/llama_cpp.rs
webapp/native/src/llm/mod.rs
webapp/native/src/llm/openai.rs
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/types/index.ts
webapp/utils/backend/Backend.ts
webapp/utils/providers/index.ts
webapp/utils/providers/openai/index.ts
webapp/utils/providers/opla/index.ts

feat: token usage speed/count

---

webapp/components/threads/Explorer.tsx

feat: sort Recents

---

webapp/.prettierignore
webapp/components/Layout.tsx
webapp/components/common/Loading/index.tsx
webapp/components/threads/Explorer.tsx
webapp/tailwind.config.ts

feat: add Loading screen

---

webapp/components/common/Statusbar/index.tsx
webapp/components/threads/Settings.tsx

feat: display created / updated

---

webapp/components/Layout.tsx
webapp/context/index.tsx
webapp/context/modals.tsx
webapp/hooks/useDataStorage.ts
webapp/native/src/main.rs
webapp/native/tauri.conf.json
webapp/types/index.ts
webapp/utils/dataStorage.ts
webapp/utils/tauri.ts

feat: save conversations in localdir

---

webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/hooks/useDataStorage.ts
webapp/hooks/useDebounceFunc.ts
webapp/hooks/useHover.ts
webapp/types/index.ts

feat: reload an assistant message

---

webapp/components/threads/Message.tsx
webapp/utils/data/conversations.ts

fix: resend messages order
fix: hide action bar when processing

feat: copy a message to clipboard

---

webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/context/modals.tsx
webapp/modals/index.tsx
webapp/modals/openai/index.tsx
webapp/types/index.ts
webapp/utils/data/index.ts

feat: delete a message

---

webapp/components/common/EditableItem/index.tsx
webapp/components/threads/Explorer.tsx
webapp/utils/data/conversations.ts

fix: edit name with border
#177

feat: ellipsis name in Explorer

---

webapp/pages/_app.tsx

feat: disable default context-menu

---

webapp/components/threads/Explorer.tsx
webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/hooks/useDebounceFunc.ts
webapp/utils/data/conversations.ts

#212 
fix: no updateAt for conversations props

fix: emptied prompt input not ok

---

webapp/components/common/Markdown/CodeBlock.tsx
webapp/components/threads/Message.tsx
webapp/hooks/useMarkdownProcessor.tsx

feat: redesign codeblock

---

webapp/components/ui/command.tsx
webapp/components/ui/context-menu.tsx
webapp/components/ui/dropdown-menu.tsx

feat: cursor-pointer for menus

---

webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/pages/_app.tsx

feat: save & submit for user message
feat: save for other messages

feat: edit message

---

package-lock.json
webapp/components/threads/Thread.tsx
webapp/components/threads/index.tsx
webapp/package.json

feat: hide explorer panel

---

webapp/components/Layout.tsx
webapp/components/common/Sidebar/index.tsx
webapp/components/models/Explorer.tsx
webapp/components/providers/Explorer.tsx
webapp/components/threads/Explorer.tsx
webapp/components/threads/Thread.tsx
webapp/native/src/api/models.rs
webapp/native/src/store.rs
webapp/native/src/utils.rs
webapp/pages/index.tsx
webapp/pages/threads/[id].tsx
webapp/pages/threads/index.tsx
webapp/types/index.ts
webapp/utils/backend/commands.ts
webapp/utils/data/models.ts
webapp/utils/string.ts

#183 
chore: fix copyright name

feat: add selectedId for page settings

---

webapp/components/common/ShortCut/index.tsx
webapp/components/models/Explorer.tsx
webapp/components/models/NewLocalModel.tsx
webapp/components/threads/Explorer.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/context/modals.tsx
webapp/modals/index.tsx
webapp/modals/models/index.tsx
webapp/native/src/data/model/mod.rs
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/native/tauri.conf.json
webapp/types/ui.ts
webapp/utils/backend/commands.ts
webapp/utils/backend/tauri.ts
webapp/utils/conversations/index.ts
webapp/utils/dataStorage.ts
webapp/utils/models/index.ts
webapp/utils/providers/llama.cpp/index.ts
webapp/utils/providers/openai/index.ts
webapp/utils/providers/opla/index.ts
webapp/utils/shortcuts.ts

feat: refactor modals typing
feat: refactor shortcuts

feat: load gguf model

---

webapp/components/common/Card/index.tsx
webapp/components/common/Parameter/index.tsx
webapp/components/icons/OpenAI.tsx
webapp/components/providers/Explorer.tsx
webapp/components/providers/opla/index.tsx
webapp/components/providers/server/index.tsx
webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/hooks/useProviderState.ts
webapp/modals/templates/NewProvider.tsx
webapp/modals/templates/providers/index.tsx
webapp/native/src/main.rs
webapp/native/src/store.rs
webapp/pages/_app.tsx
webapp/types/index.ts

feat: setup provider server

---

webapp/components/models/NewLocalModel.tsx
webapp/components/models/SearchHuggingFaceHub.tsx
webapp/components/providers/Explorer.tsx
webapp/components/threads/Thread.tsx
webapp/components/ui/command.tsx
webapp/native/src/api/hf.rs
webapp/native/src/api/mod.rs
webapp/native/src/data/mod.rs
webapp/native/src/data/model/mod.rs
webapp/native/src/main.rs
webapp/types/index.ts
webapp/utils/backend/commands.ts
webapp/utils/backend/tauri.ts
webapp/utils/providers/hf/index.ts

feat: search models on Hugging Face hub

---

webapp/components/common/AlertDialog/index.tsx
webapp/components/common/Dropdown/index.tsx
webapp/components/common/Sidebar/index.tsx
webapp/components/common/SplitView/index.tsx
webapp/components/models/Explorer.tsx
webapp/components/models/NewLocalModel.tsx
webapp/components/models/SearchHuggingFaceHub.tsx
webapp/components/models/index.tsx
webapp/components/providers/Explorer.tsx
webapp/components/threads/Explorer.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/components/threads/index.tsx
webapp/context/modals.tsx
webapp/hooks/useProviderState.ts
webapp/modals/models/index.tsx
webapp/modals/openai/index.tsx
webapp/modals/settings/appearance/index.tsx
webapp/modals/templates/NewProvider.tsx

chore: refactor const onXXX to const handleXXX

---

webapp/components/threads/Thread.tsx
webapp/components/threads/index.tsx

feat: optimize thread messages loading

---

.github/workflows/publish.yml
.github/workflows/test.yml
webapp/components/icons/OpenAI.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx

feat: display ChatGPT icon in Conversation

---

webapp/hooks/useCollectionStorage.ts
webapp/native/assets/opla_default_config.json
webapp/utils/backend/Backend.ts
webapp/utils/dataStorage.ts
webapp/utils/providers/llama.cpp/schema.ts

fix: crash at first start

---

webapp/components/common/PromptCard/index.tsx
webapp/components/threads/PromptsGrid.tsx
webapp/hooks/useFetch.ts

feat: fetch default prompts from url json

---

webapp/components/common/Statusbar/index.tsx
webapp/native/Cargo.toml
webapp/native/src/main.rs
webapp/native/src/sys.rs
webapp/types/index.ts
webapp/utils/backend/commands.ts

feat: display cpus usage

---

webapp/components/common/Statusbar/index.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/context/index.tsx
webapp/hooks/useCollectionStorage.ts
webapp/utils/data/conversations.ts

feat: display message history

---

webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/index.tsx

feat: display debug panel in thread settings

---

webapp/components/providers/Provider.tsx
webapp/components/providers/opla/Actions.tsx
webapp/components/providers/opla/index.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Thread.tsx
webapp/hooks/useBackendContext.tsx
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/types/index.ts
webapp/utils/backend/Backend.ts

feat: Provider page view logs and error

---

webapp/components/threads/Archive.tsx
webapp/components/threads/Conversation.tsx
webapp/components/threads/Message.tsx
webapp/components/threads/Prompt.tsx
webapp/components/threads/Settings.tsx
webapp/components/threads/Thread.tsx
webapp/types/index.ts
webapp/utils/data/conversations.ts
webapp/utils/data/index.ts
webapp/utils/misc.ts

feat: add/remove file to a conversation

---

package-lock.json
webapp/components/assistants/Assistant.tsx
webapp/components/assistants/Explorer.tsx
webapp/components/assistants/index.tsx
webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/common/Explorer/index.tsx
webapp/components/common/RecordView/Header.tsx
webapp/components/common/RecordView/Toolbar.tsx
webapp/components/common/RecordView/index.tsx
webapp/components/common/Sidebar/index.tsx
webapp/components/providers/Provider.tsx
webapp/components/threads/Presets.tsx
webapp/hooks/useAssistantStoreContext.tsx
webapp/hooks/useShortcuts.tsx
webapp/package.json
webapp/pages/assistants/[id].tsx
webapp/pages/assistants/index.tsx
webapp/stores/assistants.ts
webapp/stores/index.ts
webapp/stores/storage.ts
webapp/types/index.ts
webapp/types/ui.ts
webapp/utils/data/index.ts
webapp/utils/data/presets.ts
webapp/utils/dataStorage.ts

feat: add assistants

---

webapp/components/assistants/Assistant.tsx
webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/common/Pastille/index.tsx
webapp/stores/index.ts
webapp/stores/storage.ts
webapp/tailwind.config.ts
webapp/utils/ui.ts

fix: pastille color (tailwind safelist)
fix: div inside span ExplorerList
#249

fix: slice storage

---

webapp/app/globals.css
webapp/components/common/Sidebar/SidebarItem.tsx
webapp/components/common/Sidebar/SidebarItems.tsx
webapp/components/common/Statusbar/index.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx

feat: orange theme

---

webapp/components/threads/Prompt.tsx
webapp/components/threads/PromptCommand.tsx
webapp/components/threads/Thread.tsx
webapp/utils/prompt.ts
webapp/utils/ui.ts

feat: hashtag/action implementation in prompt

---

webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/utils/data/models.ts

fix: when a conversation use a disabled Provider it display "Choose a provider" instead of the provider

---

Cargo.lock
webapp/components/providers/Provider.tsx
webapp/components/providers/opla/Actions.tsx
webapp/hooks/useBackendContext.tsx
webapp/hooks/useProviderState.ts
webapp/native/Cargo.toml
webapp/native/src/main.rs
webapp/native/src/server.rs
webapp/utils/backend/Backend.ts

fix: handle start, stop, restart errors correctly

---

webapp/components/common/EditableItem/index.tsx
webapp/components/threads/Explorer.tsx
webapp/utils/conversations/index.ts

fix: regression new conversation name end with '...'

---

webapp/components/icons/Opla.tsx
webapp/components/threads/Prompt.tsx
webapp/components/threads/PromptCommand.tsx
webapp/components/threads/Settings.tsx
webapp/components/ui/textarea.tsx
webapp/hooks/useAutoResizeTextArea.ts
webapp/hooks/useBackendContext.tsx
webapp/hooks/useMarkdownProcessor.tsx
webapp/hooks/useScroll.ts
webapp/utils/ui/calculateNodeHeight.ts
webapp/utils/ui/index.ts

fix: area autoresize wrong at prompt start

---

webapp/components/threads/PromptCommand.tsx
webapp/utils/prompt.ts

fix: wrong display with 2 spaces or more in prompt

---

webapp/components/common/Parameter/index.tsx
webapp/hooks/useBackendContext.tsx
webapp/hooks/useProviderState.ts
webapp/types/index.ts

fix: refactor server parameters validation

---

webapp/components/common/ModelInfos/index.tsx
webapp/components/models/Explorer.tsx
webapp/components/models/Model.tsx
webapp/components/models/index.tsx
webapp/components/threads/Thread.tsx
webapp/components/threads/ThreadMenu.tsx
webapp/components/ui/Pills/index.tsx
webapp/tailwind.config.ts
webapp/types/index.ts

feat: display Model infos

---

webapp/components/views/Threads/Prompt.tsx
webapp/components/views/Threads/PromptCommandInput.tsx
webapp/components/views/Threads/Thread.tsx
webapp/utils/commands/Command.ts
webapp/utils/commands/index.ts
webapp/utils/commands/types.ts
webapp/utils/parsers/index.ts
webapp/utils/parsers/validator.ts

feat: refactor prompt commands management

---

webapp/components/views/Threads/Thread.tsx
webapp/utils/commands/index.ts
webapp/utils/data/messages.ts

feat: prompt imagine action implementation mockup

---

webapp/components/common/Explorer/ExplorerGroup.tsx
webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/ui/button.tsx
webapp/components/views/Assistants/Assistant.tsx
webapp/components/views/Threads/Explorer/AssistantsList.tsx
webapp/components/views/Threads/Explorer/index.tsx
webapp/stores/assistants.ts

feat: display assistants in Threads Explorer

---

webapp/components/common/ContentView/Header.tsx
webapp/components/common/ContentView/index.tsx
webapp/components/common/EditableItem/index.tsx
webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/views/Assistants/Assistant.tsx
webapp/components/views/Threads/Explorer/index.tsx
webapp/components/views/Threads/Thread.tsx
webapp/components/views/Threads/ThreadMenu.tsx

feat: use ContentView for Thread

---

webapp/components/views/Threads/Thread.tsx
webapp/context/index.tsx
webapp/types/index.ts
webapp/utils/commands/index.ts
webapp/utils/commands/types.ts
webapp/utils/providers/index.ts

feat: implements stream / provider_key prompt commands

---

webapp/components/views/Threads/Menu/AssistantMenu.tsx
webapp/components/views/Threads/Menu/index.tsx
webapp/types/ui.ts
webapp/utils/data/assistants.ts
webapp/utils/data/models.ts

feat: display and select assistant targets in Threads

---

webapp/components/views/Threads/Menu/AssistantMenu.tsx
webapp/components/views/Threads/Thread.tsx
webapp/components/views/Threads/index.tsx
webapp/utils/data/conversations.ts
webapp/utils/providers/opla/index.ts
webapp/utils/services/index.ts

feat: use assistant and selected target when sending message

---

webapp/components/common/EditPresets/index.tsx
webapp/components/views/Threads/Settings.tsx

fix: regression settings preset height is not ok

---

webapp/components/common/Parameter/index.tsx

fix: wrong display of disabled Parameter url

---

webapp/components/views/Threads/Conversation/ConversationList.tsx
webapp/hooks/useScroll.ts

fix: conversation scrollPosition 100% is not ok

---

webapp/components/views/Threads/Prompt.tsx
webapp/components/views/Threads/PromptCommandInput.tsx

fix: : in Prompt selecting text reveal hidden text

---

webapp/components/views/Threads/Message.tsx
webapp/components/views/Threads/Thread.tsx

fix: correct message.status error

---

webapp/components/views/Threads/Settings.tsx
webapp/components/views/Threads/index.tsx
webapp/types/ui.ts

Ooops direct commit to main in previous

fix: don't display other conversation errors in debug settings

---

package-lock.json
webapp/utils/commands/index.ts
webapp/utils/data/models.ts
webapp/utils/services/index.ts

fix: inline model not found

---

webapp/components/views/Threads/Thread.tsx
webapp/utils/commands/index.ts
webapp/utils/data/messages.ts

fix: resend /imagine don't work correctly

---

webapp/components/common/AssistantIcon/index.tsx
webapp/components/common/AvatarView/index.tsx
webapp/components/views/AssistantsStore/AssistantCard.tsx
webapp/components/views/Threads/Archive.tsx
webapp/components/views/Threads/Conversation/ConversationList.tsx
webapp/components/views/Threads/Conversation/MessageView.tsx
webapp/components/views/Threads/Conversation/index.tsx
webapp/components/views/Threads/Thread.tsx
webapp/types/index.ts

feat: refactor conversationList and Archive

feat: display assistant icon and name in conversation's messages

---

webapp/components/views/Threads/Header/ModelMenu.tsx
webapp/types/ui.ts
webapp/utils/data/models.ts

fix: ModelMenu Warning: Encountered two children with the same key

---

webapp/components/ui/command.tsx
webapp/components/views/Threads/Header/index.tsx
webapp/components/views/Threads/PromptCommandInput.tsx
webapp/components/views/Threads/Thread.tsx
webapp/utils/services/index.ts

fix: assistant empty target model selection

fix: disabled commanditem

---

webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/ui/ContextMenu/ContextMenuList.tsx
webapp/components/views/Threads/Explorer/AssistantsList.tsx
webapp/components/views/Threads/Header/AssistantMenu.tsx
webapp/components/views/Threads/Header/AssistantTitle.tsx
webapp/components/views/Threads/Header/index.tsx
webapp/stores/assistants.ts
webapp/types/index.ts
webapp/utils/services/index.ts

fix: ThreadHeader conversation undefined

feat: Threads explorer contextmenu to edit/hide assistants

---

webapp/native/src/data/model/mod.rs
webapp/native/src/main.rs

fix: model state stay equal to downloading

---

webapp/components/common/Explorer/ExplorerList.tsx
webapp/components/views/Threads/Explorer/index.tsx

feat: resize ExplorerGroup height

---

webapp/components/common/Explorer/ExplorerGroup.tsx

fix: multiline assistants title in Threads Explorer

---

webapp/components/ui/Pills/index.tsx
webapp/components/views/Models/Explorer.tsx

fix: localmodel item display in models explorer

---

Cargo.lock
webapp/components/ui/input-icon.tsx
webapp/components/ui/input.tsx
webapp/components/ui/textarea.tsx
webapp/tailwind.config.ts

feat: set caret color as primary

---

webapp/components/views/Models/Model.tsx

fix: model description text is cut

---

webapp/utils/data/models.ts
webapp/utils/services/index.ts

…ject (evaluating 'modelIdOrName.toLowerCase') #523

fix: null is not an object finModel #523

---

webapp/components/common/EmptyView/index.tsx

fix: hover should have a unique key #554

---

webapp/utils/providers/index.ts

fix: use gpt-3.5 turbo gives invalid modelid

---

Cargo.lock
webapp/native/Cargo.toml
webapp/native/src/llm/openai.rs

fix: rust reqwest new version is not building #584

---

webapp/components/views/Models/NewLocalModel.tsx
webapp/components/views/Models/SearchHuggingFaceHub.tsx

feat: enhance local model search display #589

---

webapp/components/views/Assistants/Explorer.tsx
webapp/components/views/AssistantsStore/index.tsx

fix: reinstall assistant from store enable it

fix: empty view only for my assistants #658

---

webapp/components/views/Threads/Thread.tsx

fix: selected model disappear after 1st input #738

---

webapp/components/views/Models/Model.tsx
webapp/components/views/Models/NewLocalModel.tsx
webapp/components/views/Threads/Conversation/index.tsx
webapp/components/views/Threads/Header/ModelMenu.tsx
webapp/components/views/Threads/Header/index.tsx
webapp/components/views/Threads/Thread.tsx
webapp/native/src/data/model/mod.rs
webapp/types/index.ts
webapp/utils/data/models.ts
webapp/utils/models/index.ts
webapp/utils/services/index.ts

feat: wip Thread refactor #705

feat: don't upload same model multiple times #653

---

webapp/components/views/Threads/Conversation/MessageView.tsx

… in non edit mode Windows #763

fix: MessageView can't select text #763

---

webapp/utils/providers/opla/index.ts

feat: local AI default stream #868

---

webapp/utils/providers/openai/index.ts

feat: add gpt-4o model from OpenAI #894

---

webapp/components/views/Threads/Conversation/ConversationContext.tsx
webapp/hooks/useBackendContext.tsx
webapp/native/src/providers/mod.rs

fix: update llama.cpp & refresh store #897

---

webapp/context/index.tsx
webapp/utils/data/conversations.ts
webapp/utils/data/messages.ts

fix: conversation name is not saved #896

---

webapp/native/src/data/workspace/project.rs
webapp/native/src/store/workspace_storage.rs
webapp/stores/constants.ts
webapp/stores/index.ts
webapp/stores/workspace.ts
webapp/types/index.ts

feat: create project #929

---

webapp/components/views/Threads/Conversation/ConversationList.tsx
webapp/components/views/Threads/Conversation/index.tsx
webapp/hooks/useScroll.ts

fix: hide scrollTo for no scroll conversation #951

---

webapp/features/Models/Model.tsx

fix: can't uninstall a local model #968

---

webapp/utils/backend/commands.ts
webapp/utils/models/index.ts

fix:error installing model invalid args 'model' #969

---

webapp/features/Threads/Prompt/PromptContext.tsx
webapp/utils/providers/index.ts

fix: promptContext crash #1420
